#pragma once$INCLUDE_GUARD_BEGIN$
$BASE_CLASS_INCLUDE$$UI_INCLUDE$
$NAMESPACE_BEGIN$
class $CLASS$$BASE_CLASS_INHERIT$$UI_INHERIT$ {
	$Q_OBJECT$

public:
	$CLASS$($SIGNATURE_DECL$);
	~$CLASS$();

private:
	$UI_DECL$
};
$NAMESPACE_END$$INCLUDE_GUARD_END$